# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/lib64/python2.7/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /usr/lib64/python2.7/site-packages/cmake/data/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /app/huang/MTCNN

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /app/huang/MTCNN

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/lib64/python2.7/site-packages/cmake/data/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/lib64/python2.7/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /app/huang/MTCNN/CMakeFiles /app/huang/MTCNN/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /app/huang/MTCNN/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mtcnn_c

# Build rule for target.
mtcnn_c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mtcnn_c
.PHONY : mtcnn_c

# fast build rule for target.
mtcnn_c/fast:
	$(MAKE) -f CMakeFiles/mtcnn_c.dir/build.make CMakeFiles/mtcnn_c.dir/build
.PHONY : mtcnn_c/fast

base64.o: base64.cpp.o

.PHONY : base64.o

# target to build an object file
base64.cpp.o:
	$(MAKE) -f CMakeFiles/mtcnn_c.dir/build.make CMakeFiles/mtcnn_c.dir/base64.cpp.o
.PHONY : base64.cpp.o

base64.i: base64.cpp.i

.PHONY : base64.i

# target to preprocess a source file
base64.cpp.i:
	$(MAKE) -f CMakeFiles/mtcnn_c.dir/build.make CMakeFiles/mtcnn_c.dir/base64.cpp.i
.PHONY : base64.cpp.i

base64.s: base64.cpp.s

.PHONY : base64.s

# target to generate assembly for a file
base64.cpp.s:
	$(MAKE) -f CMakeFiles/mtcnn_c.dir/build.make CMakeFiles/mtcnn_c.dir/base64.cpp.s
.PHONY : base64.cpp.s

get_token.o: get_token.cpp.o

.PHONY : get_token.o

# target to build an object file
get_token.cpp.o:
	$(MAKE) -f CMakeFiles/mtcnn_c.dir/build.make CMakeFiles/mtcnn_c.dir/get_token.cpp.o
.PHONY : get_token.cpp.o

get_token.i: get_token.cpp.i

.PHONY : get_token.i

# target to preprocess a source file
get_token.cpp.i:
	$(MAKE) -f CMakeFiles/mtcnn_c.dir/build.make CMakeFiles/mtcnn_c.dir/get_token.cpp.i
.PHONY : get_token.cpp.i

get_token.s: get_token.cpp.s

.PHONY : get_token.s

# target to generate assembly for a file
get_token.cpp.s:
	$(MAKE) -f CMakeFiles/mtcnn_c.dir/build.make CMakeFiles/mtcnn_c.dir/get_token.cpp.s
.PHONY : get_token.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/mtcnn_c.dir/build.make CMakeFiles/mtcnn_c.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/mtcnn_c.dir/build.make CMakeFiles/mtcnn_c.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/mtcnn_c.dir/build.make CMakeFiles/mtcnn_c.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... mtcnn_c"
	@echo "... base64.o"
	@echo "... base64.i"
	@echo "... base64.s"
	@echo "... get_token.o"
	@echo "... get_token.i"
	@echo "... get_token.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

